// Derived verbatim from frontend/abi/Sorphera.json. Do not edit the contract export.
export const sorpheraAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "owner_", type: "address", internalType: "address" },
      { name: "factory_", type: "address", internalType: "address" },
      { name: "coordinator_", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "DEFAULT_PRICE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "FEE_BPS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_TICKETS_PER_TX",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "WEEK",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "acceptOwner",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "acquisitionOpen",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "id", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "buy",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "id", type: "uint256", internalType: "uint256" },
      {
        name: "picks",
        type: "tuple[]",
        internalType: "struct Sorphera.Pick[]",
        components: [
          { name: "main", type: "uint8[3]", internalType: "uint8[3]" },
          { name: "bonus", type: "uint8", internalType: "uint8" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "claimETH",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "origin", type: "uint256", internalType: "uint256" },
      { name: "ids", type: "uint256[]", internalType: "uint256[]" },
      { name: "recipient", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimedETH",
    inputs: [
      { name: "", type: "uint8", internalType: "uint8" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "close",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "id", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "combinationKey",
    inputs: [
      { name: "main", type: "uint8[3]", internalType: "uint8[3]" },
      { name: "bonus", type: "uint8", internalType: "uint8" },
    ],
    outputs: [{ name: "", type: "uint32", internalType: "uint32" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "configureRandomness",
    inputs: [
      {
        name: "c",
        type: "tuple",
        internalType: "struct Sorphera.RandomConfig",
        components: [
          { name: "subscription", type: "uint256", internalType: "uint256" },
          { name: "keyHash", type: "bytes32", internalType: "bytes32" },
          { name: "confirmations", type: "uint16", internalType: "uint16" },
          { name: "callbackGas", type: "uint32", internalType: "uint32" },
          { name: "nativePayment", type: "bool", internalType: "bool" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "configureRules",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      {
        name: "r",
        type: "tuple",
        internalType: "struct Sorphera.Rules",
        components: [
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "firstCutoff", type: "uint256", internalType: "uint256" },
          { name: "drawDelay", type: "uint256", internalType: "uint256" },
          { name: "settlementDelay", type: "uint256", internalType: "uint256" },
          { name: "maxFee", type: "uint256", internalType: "uint256" },
          { name: "maxTotal", type: "uint256", internalType: "uint256" },
          { name: "minValue", type: "uint256", internalType: "uint256" },
          { name: "slippage", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "configureVRFReserve",
    inputs: [
      { name: "linkBalance", type: "uint96", internalType: "uint96" },
      { name: "nativeBalance", type: "uint96", internalType: "uint96" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "coordinator",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IVRF" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "credit",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "id", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "currentGroup",
    inputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deploymentChainId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "entitlement",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "origin", type: "uint256", internalType: "uint256" },
      { name: "ticket", type: "uint256", internalType: "uint256" },
      { name: "claimant", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "count", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "factory",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract SorpheraVaultFactory",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "finalize",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "id", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "finalizeTieBreak",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "id", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "futureRules",
    inputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    outputs: [
      { name: "price", type: "uint256", internalType: "uint256" },
      { name: "firstCutoff", type: "uint256", internalType: "uint256" },
      { name: "drawDelay", type: "uint256", internalType: "uint256" },
      { name: "settlementDelay", type: "uint256", internalType: "uint256" },
      { name: "maxFee", type: "uint256", internalType: "uint256" },
      { name: "maxTotal", type: "uint256", internalType: "uint256" },
      { name: "minValue", type: "uint256", internalType: "uint256" },
      { name: "slippage", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRound",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "id", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct Sorphera.Round",
        components: [
          {
            name: "status",
            type: "uint8",
            internalType: "enum Sorphera.Status",
          },
          { name: "group", type: "uint256", internalType: "uint256" },
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "start", type: "uint256", internalType: "uint256" },
          { name: "cutoff", type: "uint256", internalType: "uint256" },
          { name: "earliestDraw", type: "uint256", internalType: "uint256" },
          {
            name: "settlementDeadline",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "vault", type: "address", internalType: "address" },
          { name: "sold", type: "uint256", internalType: "uint256" },
          { name: "fees", type: "uint256", internalType: "uint256" },
          { name: "requestId", type: "uint256", internalType: "uint256" },
          { name: "requestedAt", type: "uint256", internalType: "uint256" },
          { name: "randomWord", type: "uint256", internalType: "uint256" },
          { name: "ordered", type: "uint8[3]", internalType: "uint8[3]" },
          { name: "bonus", type: "uint8", internalType: "uint8" },
          { name: "winningKey", type: "uint32", internalType: "uint32" },
          { name: "matches", type: "uint256", internalType: "uint256" },
          { name: "winningTicket", type: "uint256", internalType: "uint256" },
          { name: "eligibleNFTs", type: "uint256", internalType: "uint256" },
          { name: "frozenNFTs", type: "uint256", internalType: "uint256" },
          {
            name: "tieBreakRequestId",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "tieBreakWord", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "groupOf",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "id", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "groups",
    inputs: [
      { name: "", type: "uint8", internalType: "uint8" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "currentRound", type: "uint256", internalType: "uint256" },
      { name: "terminalRound", type: "uint256", internalType: "uint256" },
      { name: "cash", type: "uint256", internalType: "uint256" },
      { name: "perTicket", type: "uint256", internalType: "uint256" },
      { name: "divisor", type: "uint256", internalType: "uint256" },
      { name: "nftCount", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isCancelled",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "id", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isTerminal",
    inputs: [
      { name: "status", type: "uint8", internalType: "enum Sorphera.Status" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "latestRound",
    inputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "launchValidated",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "matchCount",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "combination", type: "uint32", internalType: "uint32" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "matchingTicket",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "combination", type: "uint32", internalType: "uint32" },
      { name: "index", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "minimumLinkBalance",
    inputs: [],
    outputs: [{ name: "", type: "uint96", internalType: "uint96" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "minimumNativeBalance",
    inputs: [],
    outputs: [{ name: "", type: "uint96", internalType: "uint96" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "name",
    inputs: [{ name: "game", type: "uint8", internalType: "uint8" }],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "openRound",
    inputs: [{ name: "game", type: "uint8", internalType: "uint8" }],
    outputs: [{ name: "id", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "operatorFees",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingOwner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "proposeOwner",
    inputs: [{ name: "next", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "randomConfig",
    inputs: [],
    outputs: [
      { name: "subscription", type: "uint256", internalType: "uint256" },
      { name: "keyHash", type: "bytes32", internalType: "bytes32" },
      { name: "confirmations", type: "uint16", internalType: "uint16" },
      { name: "callbackGas", type: "uint32", internalType: "uint32" },
      { name: "nativePayment", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rawFulfillRandomWords",
    inputs: [
      { name: "requestId", type: "uint256", internalType: "uint256" },
      { name: "words", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "recordNFT",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "securedAt", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "releasedFees",
    inputs: [
      { name: "", type: "uint8", internalType: "uint8" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "requestDraw",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "id", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "requestTieBreak",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "id", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "requests",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "round", type: "uint256", internalType: "uint256" },
      { name: "exists", type: "bool", internalType: "bool" },
      { name: "tieBreak", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "roundMinimumVRFBalance",
    inputs: [
      { name: "", type: "uint8", internalType: "uint8" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint96", internalType: "uint96" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "roundRandomConfig",
    inputs: [
      { name: "", type: "uint8", internalType: "uint8" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "subscription", type: "uint256", internalType: "uint256" },
      { name: "keyHash", type: "bytes32", internalType: "bytes32" },
      { name: "confirmations", type: "uint16", internalType: "uint16" },
      { name: "callbackGas", type: "uint32", internalType: "uint32" },
      { name: "nativePayment", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "salesEnabled",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "seedFor",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "word", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setSalesEnabled",
    inputs: [{ name: "enabled", type: "bool", internalType: "bool" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "tickets",
    inputs: [
      { name: "", type: "uint8", internalType: "uint8" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "player", type: "address", internalType: "address" },
      { name: "combination", type: "uint32", internalType: "uint32" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tieBreakSeedFor",
    inputs: [
      { name: "game", type: "uint8", internalType: "uint8" },
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "requestId", type: "uint256", internalType: "uint256" },
      { name: "word", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalLiabilities",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "validateLaunch",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawOperator",
    inputs: [
      { name: "recipient", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "Cancelled",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "round",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "available",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "tickets",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Claimed",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "round",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "ticket",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "recipient",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DrawRequested",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "round",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "requestId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "frozenNFTs",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DustCarried",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "group",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FeesReleased",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "round",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InventoryRecorded",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "originRound",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "group",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "count",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "event", name: "LaunchValidated", inputs: [], anonymous: false },
  {
    type: "event",
    name: "OperatorWithdrawal",
    inputs: [
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipAccepted",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipProposed",
    inputs: [
      { name: "next", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PrizeCredited",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "originRound",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "group",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RandomnessConfigured",
    inputs: [
      {
        name: "config",
        type: "tuple",
        indexed: false,
        internalType: "struct Sorphera.RandomConfig",
        components: [
          { name: "subscription", type: "uint256", internalType: "uint256" },
          { name: "keyHash", type: "bytes32", internalType: "bytes32" },
          { name: "confirmations", type: "uint16", internalType: "uint16" },
          { name: "callbackGas", type: "uint32", internalType: "uint32" },
          { name: "nativePayment", type: "bool", internalType: "bool" },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RandomnessStored",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "round",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "requestId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "word",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Result",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "round",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "ordered",
        type: "uint8[3]",
        indexed: false,
        internalType: "uint8[3]",
      },
      { name: "bonus", type: "uint8", indexed: false, internalType: "uint8" },
      {
        name: "combination",
        type: "uint32",
        indexed: false,
        internalType: "uint32",
      },
      {
        name: "matches",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "winningTicket",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Rollover",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "round",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "group",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "cash",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "NFTs",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoundClosed",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "round",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "tickets",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoundOpened",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "round",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "group",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "vault",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "start",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "cutoff",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "earliestDraw",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "settlementDeadline",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "price",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RulesConfigured",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "rules",
        type: "tuple",
        indexed: false,
        internalType: "struct Sorphera.Rules",
        components: [
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "firstCutoff", type: "uint256", internalType: "uint256" },
          { name: "drawDelay", type: "uint256", internalType: "uint256" },
          { name: "settlementDelay", type: "uint256", internalType: "uint256" },
          { name: "maxFee", type: "uint256", internalType: "uint256" },
          { name: "maxTotal", type: "uint256", internalType: "uint256" },
          { name: "minValue", type: "uint256", internalType: "uint256" },
          { name: "slippage", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SalesEnabled",
    inputs: [
      { name: "enabled", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TicketBought",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "round",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "ticket",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "player",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "combination",
        type: "uint32",
        indexed: false,
        internalType: "uint32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TieBreakRandomnessStored",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "round",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "requestId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "word",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TieBreakRequested",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "round",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "requestId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TieBreakRequired",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "round",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "matches",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TieBreakResult",
    inputs: [
      { name: "game", type: "uint8", indexed: true, internalType: "uint8" },
      {
        name: "round",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "requestId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "winningTicket",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "VRFReserveConfigured",
    inputs: [
      {
        name: "minimumLinkBalance",
        type: "uint96",
        indexed: false,
        internalType: "uint96",
      },
      {
        name: "minimumNativeBalance",
        type: "uint96",
        indexed: false,
        internalType: "uint96",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "MissingCoordinatorCode",
    inputs: [
      { name: "dependency", type: "address", internalType: "address" },
      { name: "chainId", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "MissingFactoryCode",
    inputs: [
      { name: "dependency", type: "address", internalType: "address" },
      { name: "chainId", type: "uint256", internalType: "uint256" },
    ],
  },
] as const;
